# Generated by Django 4.2.27 on 2026-01-09 21:35

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('interviews', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('skill_tag', models.CharField(help_text="e.g., 'communication.star', 'backend.django.auth'", max_length=100, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('steps_json', models.JSONField(default=list, help_text='Daily plan structure array with day, topic, drills, mini_mock, quick_test')),
                ('difficulty', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], max_length=20)),
                ('duration_minutes', models.PositiveIntegerField(help_text='Estimated time per day')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Plan Template',
                'verbose_name_plural': 'Plan Templates',
                'db_table': 'plan_templates',
                'ordering': ['skill_tag'],
            },
        ),
        migrations.CreateModel(
            name='UpgradePlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('duration_days', models.PositiveIntegerField(help_text='7 or 14 days')),
                ('plan_json', models.JSONField(default=dict, help_text='Complete plan structure with strengths, weaknesses, learning_objectives, daily_plans, next_interview')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upgrade_plans', to='interviews.interviewsession')),
            ],
            options={
                'verbose_name': 'Upgrade Plan',
                'verbose_name_plural': 'Upgrade Plans',
                'db_table': 'upgrade_plans',
                'ordering': ['-created_at'],
                'unique_together': {('session', 'duration_days')},
            },
        ),
    ]
