# Generated by Django 4.2.27 on 2026-01-09 19:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('roles', '0001_initial'),
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterviewSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role_source', models.CharField(choices=[('suggestion', 'Suggestion'), ('catalog', 'Catalog'), ('custom', 'Custom')], default='catalog', max_length=20)),
                ('level', models.CharField(choices=[('junior', 'Junior'), ('mid', 'Mid-level'), ('senior', 'Senior')], max_length=10)),
                ('type', models.CharField(choices=[('hr', 'HR'), ('technical', 'Technical'), ('case', 'Case Study'), ('mixed', 'Mixed')], max_length=20)),
                ('status', models.CharField(choices=[('created', 'Created'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('abandoned', 'Abandoned')], default='created', max_length=20)),
                ('overall_score', models.IntegerField(blank=True, help_text='Score from 0-100', null=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interview_sessions', to='profiles.profile')),
                ('role_selected', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='interview_sessions', to='roles.rolecatalog')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interview_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Interview Session',
                'verbose_name_plural': 'Interview Sessions',
                'db_table': 'interview_sessions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InterviewQuestion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order', models.PositiveIntegerField(help_text='Question sequence number')),
                ('question_text', models.TextField()),
                ('category', models.CharField(choices=[('hr', 'HR'), ('technical', 'Technical'), ('case', 'Case Study'), ('behavioral', 'Behavioral')], max_length=20)),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], max_length=10)),
                ('skill_tags_json', models.JSONField(default=list, help_text='List of skill tags assessed by this question')),
                ('is_followup', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parent_question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='followup_questions', to='interviews.interviewquestion')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='interviews.interviewsession')),
            ],
            options={
                'verbose_name': 'Interview Question',
                'verbose_name_plural': 'Interview Questions',
                'db_table': 'interview_questions',
                'ordering': ['session', 'order'],
                'unique_together': {('session', 'order')},
            },
        ),
        migrations.CreateModel(
            name='InterviewAnswer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('answer_text', models.TextField()),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('time_seconds', models.PositiveIntegerField(help_text='Time taken to answer in seconds')),
                ('scores_json', models.JSONField(default=dict, help_text='Rubric scores: structure, relevance, technical_accuracy, depth, communication')),
                ('feedback_json', models.JSONField(default=dict, help_text='Generated feedback: strengths, weaknesses, improvements')),
                ('skill_tags_json', models.JSONField(default=list, help_text='Skills assessed in this answer')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('question', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='answer', to='interviews.interviewquestion')),
            ],
            options={
                'verbose_name': 'Interview Answer',
                'verbose_name_plural': 'Interview Answers',
                'db_table': 'interview_answers',
                'ordering': ['submitted_at'],
            },
        ),
    ]
