# Generated by Django 4.2.27 on 2026-01-09 19:46

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoleCatalog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, unique=True)),
                ('category', models.CharField(choices=[('backend', 'Backend'), ('frontend', 'Frontend'), ('fullstack', 'Full-stack'), ('devops', 'DevOps'), ('data', 'Data'), ('product', 'Product'), ('design', 'Design'), ('mobile', 'Mobile'), ('qa', 'QA'), ('other', 'Other')], max_length=20)),
                ('keywords_json', models.JSONField(default=list, help_text='List of keywords for matching')),
                ('description', models.TextField(blank=True)),
                ('level_keywords_json', models.JSONField(blank=True, default=dict, help_text='Keywords for different experience levels')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Role Catalog',
                'verbose_name_plural': 'Role Catalog',
                'db_table': 'role_catalog',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='RoleSuggestion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('score', models.DecimalField(decimal_places=2, help_text='Similarity score from 0.00 to 1.00', max_digits=3)),
                ('reasons_json', models.JSONField(default=list, help_text='List of reasons for this suggestion')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cv_document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_suggestions', to='profiles.cvdocument')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suggestions', to='roles.rolecatalog')),
            ],
            options={
                'verbose_name': 'Role Suggestion',
                'verbose_name_plural': 'Role Suggestions',
                'db_table': 'role_suggestions',
                'ordering': ['-score', '-created_at'],
                'unique_together': {('cv_document', 'role')},
            },
        ),
    ]
